// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVTXUxO3_dvECXuFWUZ2DEcJaNXPQ0NFc',
    appId: '1:375712346134:web:a1cfc648de22e883168537',
    messagingSenderId: '375712346134',
    projectId: 'academiaandsport',
    authDomain: 'academiaandsport.firebaseapp.com',
    storageBucket: 'academiaandsport.firebasestorage.app',
    measurementId: 'G-K9QQHHZR57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5JdPvSbvthiV1OZbERsdNNcKUNLqy6ww',
    appId: '1:375712346134:android:83bd7c1ac166ae25168537',
    messagingSenderId: '375712346134',
    projectId: 'academiaandsport',
    storageBucket: 'academiaandsport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDx1q2y37FGQ1Kid5eW5_KD6LjlSfe_h0',
    appId: '1:375712346134:ios:c60f6d25588e4c96168537',
    messagingSenderId: '375712346134',
    projectId: 'academiaandsport',
    storageBucket: 'academiaandsport.firebasestorage.app',
    iosBundleId: 'com.example.appAndsport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDx1q2y37FGQ1Kid5eW5_KD6LjlSfe_h0',
    appId: '1:375712346134:ios:c60f6d25588e4c96168537',
    messagingSenderId: '375712346134',
    projectId: 'academiaandsport',
    storageBucket: 'academiaandsport.firebasestorage.app',
    iosBundleId: 'com.example.appAndsport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVTXUxO3_dvECXuFWUZ2DEcJaNXPQ0NFc',
    appId: '1:375712346134:web:00e0a2c15c27aa9b168537',
    messagingSenderId: '375712346134',
    projectId: 'academiaandsport',
    authDomain: 'academiaandsport.firebaseapp.com',
    storageBucket: 'academiaandsport.firebasestorage.app',
    measurementId: 'G-53N1R0FHM0',
  );
}
